#include "./../../include/core/player.h"
#include <stdio.h>
#include <stdbool.h>


// Fichier d'initialisation du joueur
// Fichier purement théorique, n'est pas pris en compte dans la compilation pour le moment

void initPlayer(Player *player, int x, int y, int w, int h) {
    player->health = 100;
    player->maxHealth = 100;
    player->damage = 20;
    player->defense = 5;
    player->rect.x = x;
    player->rect.y = y;
    player->rect.w = w;
    player->rect.h = h;
    player->arrowCount = 3;
    player->maxArrows = 3;
    player->lastRegenTime = SDL_GetTicks();
    player->lastArrowTime = SDL_GetTicks();
    player->lastLightningUse = 0;
    player->lightningCooldown = 60000;
    player->lightningReady = true;
}

void regenerateHealth(Player *player) {
    Uint32 currentTime = SDL_GetTicks();
    if (currentTime - player->lastRegenTime >= 180000) {
        int regenAmount = player->maxHealth * 0.15;
        player->health += regenAmount;
        if (player->health > player->maxHealth) {
            player->health = player->maxHealth;
        }
        player->lastRegenTime = currentTime;
        printf("Player health regenerated by %d points. Current health: %d\n", regenAmount, player->health);
    }
}

void recoverArrow(Player *player) {
    Uint32 currentTime = SDL_GetTicks();
    if (player->arrowCount < player->maxArrows && currentTime - player->lastArrowTime >= 15000) { // Toutes les 15 secondes
        player->arrowCount++;
        player->lastArrowTime = currentTime;
        printf("Player recovered an arrow. Current arrows: %d\n", player->arrowCount);
    }
}

void swordAttack(Player *player) {
    printf("Player performed a sword attack! Damage dealt: %d\n", player->damage);
}

void arrowAttack(Player *player) {
    if (player->arrowCount > 0) {
        player->arrowCount--;
        printf("Player shot an arrow! Remaining arrows: %d\n", player->arrowCount);
    } else {
        printf("No arrows left to shoot!\n");
    }
}

void lightningAttack(Player *player) {
    Uint32 currentTime = SDL_GetTicks();
    if (player->lightningReady) {
        player->lightningReady = false;
        player->lastLightningUse = currentTime;
        printf("Player used a lightning attack! Area damaged.\n");
    } else {
        Uint32 remainingCooldown = player->lightningCooldown - (currentTime - player->lastLightningUse);
        if (remainingCooldown <= 0) {
            player->lightningReady = true;
            printf("Lightning attack is now ready!\n");
        } else {
            printf("Lightning attack is on cooldown! Time remaining: %d ms\n", remainingCooldown);
        }
    }
}

void takeDamage(Player *player, int damage) {
    int effectiveDamage = damage - player->defense;
    if (effectiveDamage < 0) effectiveDamage = 0;
    player->health -= effectiveDamage;
    if (player->health < 0) player->health = 0;
    printf("Player took %d damage. Current health: %d\n", effectiveDamage, player->health);
}

void updatePlayer(Player *player) {
    regenerateHealth(player);
    recoverArrow(player);
    Uint32 currentTime = SDL_GetTicks();
    if (!player->lightningReady && (currentTime - player->lastLightningUse >= player->lightningCooldown)) {
        player->lightningReady = true;
        printf("Lightning attack is ready!\n");
    }
}
